import random
import json
from datetime import datetime, timedelta

random.seed(42)

AUTHORS = [
    {"name": "Sarah Mitchell", "avatar": "👩\u200d💼", "verified": True, "bio": "Anchor at Bloomberg"},
    {"name": "Rajeev Chandrasekhar", "avatar": "🇮🇳", "verified": True, "bio": "Former Minister of State for IT, India"},
    {"name": "Vitalik Buterin", "avatar": "🔷", "verified": True, "bio": "Ethereum co-founder"},
    {"name": "Chamath Palihapitiya", "avatar": "🚀", "verified": True, "bio": "Investor, Social Capital CEO"},
    {"name": "Nassim Nicholas Taleb", "avatar": "📚", "verified": True, "bio": "Author of The Black Swan"},
    {"name": "Balaji Srinivasan", "avatar": "🌐", "verified": True, "bio": "Technologist, investor, writer"},
    {"name": "Aarav Patel", "avatar": "👨\u200d💻", "verified": True, "bio": "Founder, TechVentures India"},
    {"name": "Meera Iyer", "avatar": "👩\u200d🔬", "verified": True, "bio": "Quant fund manager, Mumbai"},
    {"name": "James Wilson", "avatar": "👨\u200d🎨", "verified": False, "bio": "FX trader, New York"},
    {"name": "Priya Sharma", "avatar": "👩\u200d💼", "verified": True, "bio": "SEBI registered analyst"},
    {"name": "Arjun Mehta", "avatar": "👨\u200d🚀", "verified": True, "bio": "Crypto research lead, WazirX"},
    {"name": "Sonia Dias", "avatar": "👩\u200d🍳", "verified": False, "bio": "Personal finance blogger"},
    {"name": "Rahul Verma", "avatar": "👨\u200d🏫", "verified": True, "bio": "Equity strategist, ICICI Securities"},
    {"name": "Emily Chen", "avatar": "👩\u200d💡", "verified": True, "bio": "AI research, Stanford"},
    {"name": "Vikram Singh", "avatar": "👨\u200d🎯", "verified": True, "bio": "Portfolio manager, HDFC AMC"},
    {"name": "Deepak Reddy", "avatar": "👨\u200d🔬", "verified": True, "bio": "Biotech analyst, PharmaTrack"},
    {"name": "Lata Menon", "avatar": "👩\u200d🎤", "verified": True, "bio": "Business news anchor, NDTV"},
    {"name": "Sanjay Kulkarni", "avatar": "👨\u200d🏋", "verified": True, "bio": "Fixed income specialist, Kotak"},
    {"name": "Ananya Gupta", "avatar": "👩\u200d💡", "verified": False, "bio": "Startup founder, angel investor"},
    {"name": "Rishi Kapoor", "avatar": "👨\u200d🍳", "verified": False, "bio": "Daily market commentary"},
    {"name": "Nandini Rajan", "avatar": "👩\u200d🎯", "verified": True, "bio": "Derivatives expert, NSE"},
    {"name": "Thomas Friedman", "avatar": "📖", "verified": True, "bio": "Columnist, NY Times"},
    {"name": "Sunita Devi", "avatar": "👩\u200d💡", "verified": False, "bio": "Gold market analyst"},
    {"name": "Karthik Suresh", "avatar": "👨\u200d🏫", "verified": True, "bio": "MBA Finance, teaching markets"},
    {"name": "Omkar Deshmukh", "avatar": "👨\u200d💻", "verified": True, "bio": "Fintech entrepreneur, Pune"},
    {"name": "Fatima Khan", "avatar": "👩\u200d💼", "verified": True, "bio": "Commodity analyst, CRISIL"},
    {"name": "Ben Thompson", "avatar": "👨\u200d🌐", "verified": True, "bio": "Stratechery author"},
    {"name": "Anjali Nair", "avatar": "👩\u200d🚀", "verified": True, "bio": "VC partner, Lightspeed India"},
    {"name": "Gopinath Rao", "avatar": "👨\u200d🎨", "verified": False, "bio": "Technical analyst, TradingView"},
    {"name": "Maya Joshi", "avatar": "👩\u200d🍳", "verified": False, "bio": "Real estate investment advisor"},
    {"name": "Kabir Malhotra", "avatar": "👨\u200d🔬", "verified": True, "bio": "Clean energy fund manager"},
    {"name": "Divya Prakash", "avatar": "👩\u200d💻", "verified": True, "bio": "Blockchain developer, Polygon"},
    {"name": "Rohan Bhat", "avatar": "👨\u200d💼", "verified": True, "bio": "Insurance sector analyst"},
    {"name": "Ishita Banerjee", "avatar": "👩\u200d🎤", "verified": True, "bio": "Economic Times columnist"},
    {"name": "Vivek Agarwal", "avatar": "👨\u200d🏫", "verified": True, "bio": "Angel investor, 50+ investments"},
    {"name": "Leela Krishnamurthy", "avatar": "👩\u200d💡", "verified": False, "bio": "Wealth management advisor"},
    {"name": "Siddharth Roy", "avatar": "👨\u200d🔥", "verified": True, "bio": "Small cap specialist"},
    {"name": "Naina Agarwal", "avatar": "👩\u200d💡", "verified": True, "bio": "MF distributor, 15 years"},
    {"name": "Arvind Krishna", "avatar": "👨\u200d🏋", "verified": True, "bio": "CEO, IBM"},
    {"name": "Lakshmi Venkatesh", "avatar": "👩\u200d🔬", "verified": True, "bio": "EV sector analyst"},
    {"name": "Nikhileshwar Reddy", "avatar": "👨\u200d🎯", "verified": True, "bio": "Hedge fund, Bengaluru"},
    {"name": "Pooja Thakur", "avatar": "👩\u200d🎨", "verified": False, "bio": "Designing financial dashboards"},
    {"name": "Rajat Bajaj", "avatar": "👨\u200d💻", "verified": True, "bio": "Algorithmic trading expert"},
    {"name": "Aisha Mohammad", "avatar": "👩\u200d🏫", "verified": True, "bio": "Islamic finance specialist"},
    {"name": "Suresh Prabhu", "avatar": "👨\u200d🏫", "verified": True, "bio": "Former Railway Minister"},
    {"name": "Trisha Gopalan", "avatar": "👩\u200d🚀", "verified": True, "bio": "Growth equity, Sequoia India"},
    {"name": "Manoj Kumar", "avatar": "👨\u200d🍳", "verified": False, "bio": "Dividend income strategist"},
    {"name": "Simran Kaur", "avatar": "👩\u200d💼", "verified": True, "bio": "Forex markets expert, RBI"},
]

# 300 unique text templates
T = [
    ("Nifty50 25K. FII Rs 12K crore.", ["Nifty50", "FII", "Bull"]),
    ("Jio tariff hike. ARPU +18%.", ["Reliance", "Jio", "Telecom"]),
    ("BTC halving: 12M post 300-500%.", ["Bitcoin", "Halving", "Cycle"]),
    ("40% equity, 20% debt, 15% gold, 15% intl, 10% crypto.", ["Portfolio", "Allocation", "Investing"]),
    ("PMI 62.3 highest. PLI working.", ["Manufacturing", "PMI", "India"]),
    ("HDFC Bank merger done. Loan +16%.", ["HDFCBank", "Banking", "Stocks"]),
    ("ETH gas $0.01 L2. Rollup roadmap.", ["Ethereum", "L2", "GasFees"]),
    ("Gold Rs 75K. RBI buying record.", ["Gold", "RBI", "CentralBanks"]),
    ("Tata Motors Q4 +22%. JLR 8.2%.", ["TataMotors", "EV", "Results"]),
    ("SIP Rs 26K Cr/month. Equity culture.", ["SIP", "MutualFunds", "Retail"]),
    ("Rule 72: 12% doubles 6Y.", ["Investing", "Compounding", "Wealth"]),
    ("VIX 11.5 5Y low. Calm = correction.", ["VIX", "Volatility", "Markets"]),
    ("IT revival: TCS Infosys Wipro double-digit.", ["IT", "TCS", "Infosys"]),
    ("Solana 100K TPS. Firedancer.", ["Solana", "Firedancer", "L1"]),
    ("Fiscal 4.8%. Roads 35km/day.", ["FiscalDeficit", "Capex", "Infrastructure"]),
    ("FMCG 52wk lows buy. Quality discount.", ["FMCG", "Contrarian", "Value"]),
    ("Adani Ports 400 MTPA record.", ["AdaniPorts", "Logistics", "GatiShakti"]),
    ("Nifty50 Index beats 80% active.", ["IndexFunds", "Passive", "MutualFunds"]),
    ("US: S&P+0.3%, NASDAQ+0.8%.", ["USMarkets", "Earnings", "Tech"]),
    ("Gold ETF Rs 4.5K Cr inflows.", ["GoldETF", "SGB", "Investing"]),
    ("Ripple wins SEC. XRP relisted.", ["Ripple", "XRP", "SEC"]),
    ("Bajaj Finance +28%. AUM Rs 4L Cr.", ["BajajFinance", "NBFC", "Results"]),
    ("Emergency 6 months expenses liquid?", ["EmergencyFund", "LiquidFunds", "Planning"]),
    ("FII sellers Rs 8K. DII absorbed.", ["FII", "DII", "Flows"]),
    ("Zomato profit 3Q. Blinkit contributing.", ["Zomato", "QuickCommerce", "Profit"]),
    ("L2 TVL $50B. Ethereum internet.", ["L2", "TVL", "Ethereum"]),
    ("UPI 18B/month. Digital > cash.", ["UPI", "DigitalPayments", "India"]),
    ("ELSS tax season. 80C utilized.", ["ELSS", "TaxPlanning", "80C"]),
    ("Buffett 45% Apple, 15% BofA.", ["Buffett", "Portfolio", "ValueInvesting"]),
    ("Power NTPC Adani Tata 52wk highs.", ["Power", "NTPC", "Energy"]),
    ("MicroStrategy +5K BTC. 250K total.", ["MicroStrategy", "Bitcoin", "Institutional"]),
    ("VIX 11 cheap options.", ["Options", "VIX", "Trading"]),
    ("Gold vs SGB vs ETF vs digital.", ["Gold", "SGB", "Comparison"]),
    ("Sold Infosys 2015 Rs 2.2K. Now 18K.", ["Mistakes", "Infosys", "Lesson"]),
    ("Sun Pharma FDA oncology.", ["SunPharma", "FDA", "Pharma"]),
    ("Flexi-cap best long-term.", ["FlexiCap", "FundSelection", "MutualFunds"]),
    ("GST Rs 2.1L Cr. Formalization.", ["GST", "Revenue", "Economy"]),
    ("Dividend 20 stocks yield>2% growth>10%.", ["Dividends", "PassiveIncome", "Strategy"]),
    ("Maruti EV SUV Dec 2026.", ["Maruti", "EV", "Auto"]),
    ("DeFi TVL $200B. Aave Uniswap.", ["DeFi", "TVL", "Aave"]),
    ("70% Nifty50 beat estimates.", ["Earnings", "Nifty50", "Broad"]),
    ("Central banks 1037T gold 2025.", ["CentralBanks", "Gold", "DeDollarization"]),
    ("Loss aversion hold losers sell winners.", ["Behavioral", "Psychology", "Investing"]),
    ("Asian Paints 53% share. 55x P/E.", ["AsianPaints", "Correction", "Value"]),
    ("Direct vs Regular: 1% = 22% less.", ["DirectPlan", "ExpenseRatio", "Wealth"]),
    ("ETH staking 4.2%. 40M ETH.", ["Ethereum", "Staking", "Yield"]),
    ("FDI $85B. Mfg +60% PLI.", ["FDI", "Manufacturing", "India"]),
    ("$84T transfer boomers to millennials.", ["WealthTransfer", "Demographics", "Trend"]),
    ("BEL Rs 76K Cr order. +12%.", ["BEL", "Defense", "OrderBook"]),
    ("BTC ETF options $5B daily.", ["BitcoinETF", "Options", "Institutional"]),
    ("Small+35% Mid+22% Large+15%.", ["SmallCap", "Breadth", "Rally"]),
    ("Akshaya Tritiya +25%. Gold demand.", ["Jewellery", "Demand", "India"]),
    ("SIP Rs 10K since 2000 = Rs 3.5Cr.", ["SIP", "Nifty50", "Consistency"]),
    ("Dr Reddy's US biosimilar $500M.", ["DrReddys", "Biosimilar", "Pharma"]),
    ("Target date: set forget auto.", ["TargetDate", "Retirement", "Funds"]),
    ("Solana mobile 1M units.", ["Solana", "Mobile", "Web3"]),
    ("Rupee 82.5. Reserves $720B.", ["Rupee", "Forex", "Reserves"]),
    ("REITs 8-10% liquid vs 12-15% illiquid.", ["RealEstate", "REITs", "Comparison"]),
    ("L&T Rs 25K Cr Aramco order.", ["LT", "OrderWin", "Infrastructure"]),
    ("Stablecoins $300B. Circle IPO.", ["Stablecoins", "USDC", "Payments"]),
    ("Gold support 72K resistance 78K.", ["Gold", "Technical", "Analysis"]),
    ("AngelList retail pre-IPO.", ["Angel", "PreIPO", "Startup"]),
    ("ICICI cross-sell 4.2. Premium.", ["ICICIBank", "CrossSell", "Banking"]),
    ("Lightning 5K BTC. L2 payments.", ["Lightning", "Bitcoin", "Payments"]),
    ("Value flexi outperforming growth.", ["Value", "FlexiCap", "Rotation"]),
    ("CAD 1.2%. Services $400B.", ["CAD", "Exports", "Services"]),
    ("Insurance not investment. Term 20x.", ["Insurance", "ULIP", "Term"]),
    ("Tata Consumer health pivot.", ["TataConsumer", "FMCG", "Health"]),
    ("NFT RWA tokenization revival.", ["NFT", "RWA", "Tokenization"]),
    ("Margin record. SEBI norms next.", ["Margin", "SEBI", "Leverage"]),
    ("DCA gold Rs 5K monthly.", ["DCA", "Gold", "Strategy"]),
    ("Say no 99%. Circle competence.", ["Focus", "CircleOfCompetence", "Discipline"]),
    ("Adani Green 15GW 25GW building.", ["AdaniGreen", "Renewable", "Energy"]),
    ("Polkadot 2.0 parachains halved.", ["Polkadot", "Interoperability", "Parachains"]),
    ("Savings 30.2%. Financial > physical.", ["Savings", "Financial", "Household"]),
    ("Risk max 2% per trade.", ["RiskManagement", "PositionSize", "Trading"]),
    ("HUL margins 25%. Pricing power.", ["HUL", "Margins", "Brands"]),
    ("NPS 80CCD(1B) Rs 50K deduction.", ["NPS", "TaxSaving", "Retirement"]),
    ("Cosmos IBC $50B monthly.", ["Cosmos", "IBC", "Interchain"]),
    ("Algo 55% NSE. Human judgment.", ["Algo", "Trading", "NSE"]),
    ("India 800T gold import. $350B idle.", ["GoldImport", "India", "Monetization"]),
    ("4% rule: retire Rs 5Cr.", ["Retirement", "FIRE", "Withdrawal"]),
    ("DMart +20%. 380 stores.", ["DMart", "Retail", "Growth"]),
    ("RWA $16B 40% monthly growth.", ["RWA", "Tokenization", "BlackRock"]),
    ("70% weekly options expire.", ["Options", "Expiry", "Trading"]),
    ("Making charges 12-15% vs SGB 0%.", ["Jewellery", "Gold", "Charges"]),
    ("Sleep well: 50% Nifty50 + bonds.", ["Portfolio", "Simple", "Index"]),
    ("Titan Rs 4L Cr. Tanishq brand.", ["Titan", "Tanishq", "Premium"]),
    ("Lightning Amazon Starbucks McDonald's.", ["Lightning", "Payments", "Adoption"]),
    ("Reserves $720B 12 months.", ["Reserves", "RBI", "Rupee"]),
    ("Cash loses Rs 70K at 7% inflation.", ["Cash", "Inflation", "Opportunity"]),
    ("Chetak 50K/month. Two-wheeler EV.", ["BajajAuto", "EV", "Chetak"]),
    ("SIP step-up 10% doubles corpus.", ["StepUp", "SIP", "Wealth"]),
    ("Solana DeFi: Jupiter billions.", ["Solana", "DeFi", "DEX"]),
    ("65% above 200 DMA healthy.", ["Breadth", "Technical", "Bull"]),
    ("Gold-silver 80:1 reverts 60:1.", ["GoldSilver", "Ratio", "Silver"]),
    ("Simple > complex. Intelligence ≠ success.", ["Simple", "Consistency", "Investing"]),
    ("BEL Rs 8K radar. 2.5% GDP.", ["BEL", "Defense", "Radar"]),
    ("ETH blobs -90% L2 cost.", ["Ethereum", "Blobs", "Danksharding"]),
    ("FDI 100% single-brand automatic.", ["FDI", "Policy", "Manufacturing"]),
    ("Rotation: IT→Banks→IT adds 3-5%.", ["Sector", "Rotation", "Strategy"]),
    ("Nestle 80x P/E premium.", ["Nestle", "Premium", "Brands"]),
    ("Hybrid 25-75% retiree 9-11%.", ["Hybrid", "Conservative", "Retirement"]),
    ("Ordinals BRC-20 Bitcoin NFTs.", ["Ordinals", "BRC20", "Bitcoin"]),
    ("SEBI F&O bigger lots fewer expiries.", ["SEBI", "F&O", "Regulation"]),
    ("Monsoon gold rural demand.", ["Monsoon", "Demand", "Rural"]),
    ("100-age = equity %.", ["Allocation", "Rule", "Age"]),
    ("Info Edge Zomato Rs 45K Cr.", ["InfoEdge", "Value", "Hidden"]),
    ("DeFi insurance $10B TVL.", ["DeFi", "Insurance", "Risk"]),
    ("Digital 22% GDP from 10%.", ["Digital", "GDP", "Economy"]),
    ("Real: 7% FD - 5% = 2%.", ["RealReturns", "Inflation", "Returns"]),
    ("Tata Chemicals soda ash EV.", ["TataChemicals", "Commodity", "EV"]),
    ("Polygon zkEVM 100 TPS.", ["Polygon", "zkEVM", "Scaling"]),
    ("5 F&O ban stocks. Check NSE.", ["F&O", "Ban", "NSE"]),
    ("SGB 2.5% vs funds liquid.", ["GoldFunds", "SGB", "Comparison"]),
    ("Pay yourself 20% automate.", ["PayFirst", "Automate", "Saving"]),
    ("Astral pipes CAGR 25%.", ["Astral", "Pipes", "Housing"]),
    ("BTC dominance 55% quality.", ["BTC", "Dominance", "Altcoins"]),
    ("Unemployment 6.8%. Urban 8.2%.", ["Unemployment", "Jobs", "Manufacturing"]),
    ("Consistent quartile 5Y+.", ["Consistency", "Returns", "Selection"]),
    ("Ola Electric 50x oversubscribed.", ["Ola", "IPO", "EV"]),
    ("Chainlink CCIP 12 chains.", ["Chainlink", "CCIP", "Oracle"]),
    ("Mcap/GDP 140%. 150% reduce.", ["McapGDP", "Valuation", "Markets"]),
    ("PBOC +30T RBI +15T gold.", ["PBOC", "CentralBank", "China"]),
    ("Career capital skill Rs 10L/yr.", ["Career", "Skills", "Income"]),
    ("CDSL 200M demat monopoly.", ["CDSL", "Demat", "Monopoly"]),
    ("Avalanche Indian stock sim.", ["Avalanche", "Subnet", "Institutional"]),
    ("Mfg surpasses UK. $5.3T.", ["Manufacturing", "UK", "Growth"]),
    ("Cab driver tips = peak.", ["Sentiment", "Contrarian", "Indicator"]),
    ("Persistent $1B deal.", ["Persistent", "Deal", "Healthcare"]),
    ("EigenLayer $15B restaking.", ["EigenLayer", "Restaking", "Yield"]),
    ("Nifty bull flag 25.5K→27K.", ["Technical", "Chart", "Nifty"]),
    ("Gold +15% USD +18% INR.", ["Gold", "Currency", "Hedge"]),
    ("Core 70% index satellite 30%.", ["Core", "Satellite", "Portfolio"]),
    ("Lupin FDA Advair $300M.", ["Lupin", "FDA", "Generics"]),
    ("Base 2M DAU. Fastest L2.", ["Base", "L2", "Coinbase"]),
    ("GST gaming 28% skill-based.", ["GST", "Gaming", "Regulation"]),
    ("10 stocks 5 sectors free lunch.", ["Diversification", "Portfolio", "Risk"]),
    ("Cochin Shipyard Rs 25K Cr.", ["CochinShipyard", "Navy", "Defense"]),
    ("Solana Pay 10K TPS.", ["SolanaPay", "Payments", "Scale"]),
    ("FII long 60% crowded.", ["FII", "Positioning", "Risk"]),
    ("Gold forecast $3,500.", ["Forecast", "Gold", "Price"]),
    ("Best time 20Y ago today.", ["Start", "Today", "Urgency"]),
    ("Godrej Africa +30%.", ["Godrej", "Africa", "Emerging"]),
    ("BTC mining ATH 800 EH/s.", ["Mining", "Difficulty", "Security"]),
    ("India Stack 1B Aadhaar 500M UPI.", ["IndiaStack", "Digital", "Infrastructure"]),
    ("Rebalancing +0.5-1%.", ["Rebalancing", "Returns", "Discipline"]),
    ("Aarti chemicals China+1.", ["AartiIndustries", "Chemicals", "PLI"]),
    ("Mina 22KB ZK blockchain.", ["Mina", "ZK", "Privacy"]),
    ("Depth 50x since 2015.", ["Microstructure", "Liquidity", "NSE"]),
    ("Buy 100 at 70 margin.", ["MarginSafety", "Value", "Buffer"]),
    ("Poly Cab CAGR 30%.", ["PolyCab", "Cables", "Growth"]),
    ("ENS 5M domains Web3.", ["ENS", "Identity", "Web3"]),
    ("Services exports $350B.", ["Services", "Exports", "IT"]),
    ("Don't invest unknown.", ["Simplicity", "Understanding", "Risk"]),
    ("Whirl appliances premium.", ["Whirlpool", "Appliances", "Premium"]),
    ("Filecoin 30 EiB storage.", ["Filecoin", "Storage", "Decentralized"]),
    ("Straddle 450 vol 2.5%.", ["Options", "Straddle", "Volatility"]),
    ("Gold accumulator 1g monthly.", ["Accumulator", "SIP", "Gold"]),
    ("FOMO panic rules before.", ["Behavior", "Rules", "Discipline"]),
    ("Mphasis mid IT 25%.", ["Mphasis", "IT", "BFSI"]),
    ("Flashbots MEV protection.", ["Flashbots", "MEV", "Protection"]),
    ("Power 150 BU peak 250GW.", ["Power", "Demand", "Data"]),
    ("Read 30min daily top 1%.", ["Learning", "Self", "Growth"]),
    ("Tata Elxsi design AI 20%.", ["TataElxsi", "Design", "AI"]),
    ("Uniswap v4 hooks programmable.", ["Uniswap", "Hooks", "AMM"]),
    ("Nifty EPS +18% 22x justified.", ["Earnings", "Valuation", "Nifty"]),
    ("Sensex 14% CAGR 20Y.", ["Index", "Nifty50", "CAGR"]),
    ("KEC T&D Rs 35K Cr.", ["KEC", "T&D", "Power"]),
    ("Optimism OP Stack standard.", ["Optimism", "Bedrock", "L2"]),
    ("FDI: IT 25% Mfg 20%.", ["FDI", "Sectors", "Diversification"]),
    ("30Y: Sensex 15% Gold 11%.", ["Returns", "AssetClass", "Comparison"]),
    ("PI Industries 25%.", ["PIIndustries", "Agrochem", "Food"]),
    ("Merge 2Y energy -99.9%.", ["Merge", "Ethereum", "Green"]),
    ("Retail 30% volumes.", ["Retail", "Democratization", "Access"]),
    ("Gold LTCG 3Y 20%.", ["Tax", "LTCG", "Gold"]),
    ("25: 5K SIP = 5Cr. 35: 1.5Cr.", ["Early", "SIP", "Compound"]),
    ("Route Mobile CPaaS doubled.", ["RouteMobile", "CPaaS", "Cloud"]),
    ("Cosmos shared security.", ["Cosmos", "Security", "Shared"]),
    ("1.44B median 28.", ["Population", "Demographic", "Youth"]),
    ("Assets > liabilities.", ["Assets", "Liabilities", "Mindset"]),
    ("Supreme pipes 20% Jal Jeevan.", ["Supreme", "Pipes", "JalJeevan"]),
    ("ZK prove without revealing.", ["ZK", "Cryptography", "Privacy"]),
    ("US debt $35T interest $1T.", ["Debt", "US", "Macro"]),
    ("Gold drivers inflation rates banks.", ["Drivers", "Price", "Fundamentals"]),
    ("DCA buy more low less high.", ["DCA", "Timing", "Strategy"]),
    ("IRCTC railway monopoly 20%.", ["IRCTC", "Monopoly", "Railways"]),
    ("Rollup: L2s L1 L3s L2s.", ["Rollup", "Modular", "Scaling"]),
    ("Steel 150M tonnes #2.", ["Steel", "Production", "Infrastructure"]),
    ("Edge info analysis temperament.", ["Edge", "SelfAwareness", "Investing"]),
    ("Chambal Fertilizers defensive.", ["Chambal", "Fertilizer", "Subsidy"]),
    ("BTC best 10Y 150% CAGR.", ["Bitcoin", "Performance", "LongTerm"]),
    ("May-Sep weak Oct-Mar strong.", ["Seasonal", "Patterns", "Strategy"]),
    ("Gold -25% vol portfolio theory.", ["Portfolio", "Theory", "Allocation"]),
    ("Index SIP 95% don't complicate.", ["Simple", "Experts", "Strategy"]),
    ("Indus Towers 5G data +30%.", ["IndusTowers", "5G", "Tower"]),
    ("EIP-1559 2M ETH burned.", ["EIP1559", "Deflationary", "Ultrasound"]),
    ("IT $300B 5.5M employed.", ["IT", "Revenue", "Employment"]),
    ("Emergency 3 mo savings 3 liquid.", ["Emergency", "Liquid", "Safety"]),
    ("Laurus API 30% China+1.", ["Laurus", "API", "Pharma"]),
    ("BTC gold correlation rising.", ["DigitalGold", "Correlation", "Bitcoin"]),
    ("Fear greed regret destroy.", ["Psychology", "Emotions", "Trading"]),
    ("Tanishq 18% online 3% SGB 0%.", ["Charges", "Cost", "Comparison"]),
    ("10-bagger: small cap large market.", ["TenBagger", "Lynch", "Growth"]),
    ("IIFL gold loan 35%.", ["IIFL", "GoldLoan", "NBFC"]),
    ("Layer 0 Polkadot Cosmos.", ["Layer0", "Interoperability", "Foundation"]),
    ("Tax/GDP 11.5% formalization.", ["Tax", "GDP", "Formalization"]),
    ("Three-fund: Nifty50 US Bonds.", ["ThreeFund", "Simple", "Portfolio"]),
    ("Kajaria tiles 15%.", ["Kajaria", "Tiles", "Housing"]),
    ("PoW vs PoS different tools.", ["PoW", "PoS", "Debate"]),
    ("Smart money bullish alpha.", ["SmartMoney", "Indicators", "Alpha"]),
    ("Gold collateral ETF margin.", ["Collateral", "ETF", "Trading"]),
    ("15% 20Y = 10x.", ["Target", "Consistent", "Compound"]),
    ("Blue Star AC 7% vs US 90%.", ["BlueStar", "AC", "Climate"]),
    ("ERC-4337 social recovery.", ["AccountAbstraction", "ERC4337", "UX"]),
    ("Real estate 10Y high launches.", ["RealEstate", "Cycle", "Sales"]),
    ("Checklist: moat market mgmt.", ["Checklist", "Quality", "Process"]),
    ("Happiest Minds 25% small cap.", ["HappiestMinds", "Digital", "SmallCap"]),
    ("Balanced maximalism + diversity.", ["Maximalism", "Diversity", "Balance"]),
    ("50 IPOs Q1 Rs 15K Cr.", ["IPO", "Primary", "Selective"]),
    ("Gold correlation: -dollar -rates.", ["Correlation", "Analysis", "Timing"]),
    ("Perfect enemy start today.", ["Perfect", "Start", "Imperfect"]),
    ("CAMS registrar monopoly.", ["CAMS", "Monopoly", "MF"]),
    ("Tokenomics supply utility governance.", ["Tokenomics", "Value", "Supply"]),
    ("EV 50% annual 15% adoption.", ["EV", "TwoWheeler", "Adoption"]),
    ("Don't check daily less look.", ["Frequency", "Anxiety", "LongTerm"]),
    ("CONCOR logistics monopoly 12%.", ["CONCOR", "Logistics", "Port"]),
    ("DeSci science on-chain.", ["DeSci", "Science", "Open"]),
    ("Put-call 0.8 max pain 24.8K.", ["PutCall", "MaxPain", "Derivatives"]),
    ("Demand: jewellery 50% inv 25%.", ["Demand", "Sectors", "Growth"]),
    ("FIRE 25x expenses.", ["FIRE", "Expenses", "Independence"]),
    ("Trent Zudio 35%.", ["Trent", "Zudio", "Retail"]),
    ("MEV $500M Flashbots.", ["MEV", "Flashbots", "Fairness"]),
    ("Insurance 4.2% vs global 7%.", ["Insurance", "Penetration", "Opportunity"]),
    ("Spend less invest more wait.", ["Simple", "Spend", "Wait"]),
    ("Jubilant same-store 12%.", ["Jubilant", "Domino", "QSR"]),
    ("Bridges $10B hacked.", ["Bridge", "Security", "Hacks"]),
    ("Nifty P/E 22x vs avg 20x.", ["PE", "Valuation", "Quantitative"]),
    ("Gold standard role increasing.", ["Standard", "Debate", "Monetary"]),
    ("Mistakes cost more than fees.", ["Mistakes", "Fees", "Cost"]),
    ("Muthoot Rs 2L Cr 28% ROE.", ["Muthoot", "GoldLoan", "Compounder"]),
    ("Web3 gaming play-to-own.", ["Gaming", "Web3", "Adoption"]),
    ("Credit 16% fastest clean.", ["Credit", "Banking", "Cycle"]),
    ("80/20 80% from 20%.", ["Pareto", "Allocation", "Decisions"]),
    ("SBI Cards 25% 100M.", ["SBI", "Cards", "Credit"]),
    ("LSD Lido 40% staked.", ["LSD", "Staking", "DeFi"]),
    ("VIX<12 buy straddles.", ["Volatility", "Straddle", "MeanReversion"]),
    ("Crisis since 1971 gold up.", ["Geopolitics", "Crisis", "Gold"]),
    ("Behavioral asymmetry rational.", ["Advantage", "Behavioral", "Rational"]),
    ("Astral 25% multi-decade.", ["Astral", "Infrastructure", "Pipes"]),
    ("Ethereum surge verge purge.", ["Roadmap", "Phases", "Ethereum"]),
    ("CAD 1.2% services offset.", ["CAD", "Remittances", "Services"]),
    ("5-10% cash optionality.", ["Cash", "Optionality", "Insurance"]),
    ("Tata Comms data center 40%.", ["TataComm", "DataCenter", "AI"]),
    ("Power+45% Defence+38% Banking+25%.", ["Sector", "YTD", "Rotation"]),
    ("ETF expense 0.5%.", ["ETF", "Expense", "Tracking"]),
    ("Birlasoft 22% manufacturing.", ["Birlasoft", "MidCap", "Digital"]),
    ("Halving +8000% +2000% +700%.", ["Halving", "History", "Cycles"]),
    ("Near FII limits supply.", ["FII", "Limits", "Supply"]),
    ("Art of nothing patience.", ["Patience", "Inactivity", "Trading"]),
    ("Taj RevPAR ATH tourism.", ["Taj", "Hotels", "Tourism"]),
    ("Tokenized treasuries $10B.", ["Treasury", "Tokenized", "TradFi"]),
    ("Impact 5-10 bps Nifty.", ["Impact", "Liquidity", "Cost"]),
    ("Jewelry resale 70-85%.", ["Resale", "Jewelry", "Value"]),
    ("Buffett what he didn't do.", ["No", "Discipline", "Buffett"]),
    ("Affle mobile 30%.", ["Affle", "Digital", "Marketing"]),
    ("On-chain whales MVRV.", ["OnChain", "Analytics", "Data"]),
    ("FDI: SG 28% Mau 18%.", ["FDI", "Source", "Routes"]),
    ("Not competition journey.", ["Personal", "Goals", "Journey"]),
    ("Kfin RTA 20%.", ["Kfin", "RTA", "MF"]),
    ("AI+Crypto autonomous payments.", ["AI", "Convergence", "Agents"]),
    ("India S&P correlation 0.3.", ["Correlation", "Global", "Independent"]),
    ("Gold supply 1.5% demand 3-4%.", ["Production", "Supply", "Demand"]),
    ("Delay costs Rs 10L/yr.", ["Delay", "Cost", "Urgency"]),
    ("Delhivery logistics tech 25%.", ["Delhivery", "Logistics", "Tech"]),
    ("Self-sovereign identity.", ["Identity", "Decentralized", "Web3"]),
    ("Labor 80% cheaper China.", ["Manufacturing", "Cost", "Competitiveness"]),
    ("Three pillars allocation cost behavior.", ["Pillars", "Fundamentals", "Success"]),
    ("Zomato = FMCG giants.", ["Zomato", "FoodTech", "QuickCommerce"]),
    ("BTC $100K ETH $5K bull.", ["BullMarket", "Recovery", "Discipline"]),
    ("Smart beta momentum quality.", ["SmartBeta", "Factor", "Strategy"]),
    ("Rural gold schemes systematic.", ["Savings", "Scheme", "Rural"]),
    ("Greatest risk not taking.", ["Risk", "Conservative", "Safe"]),
    ("KPIT auto 30% CAGR.", ["KPIT", "Auto", "Software"]),
    ("1% global = $1T.", ["Institutional", "Allocation", "Demand"]),
    ("Services PMI 61.5 24mo.", ["Services", "PMI", "Expansion"]),
    ("Psychology of Money Housel.", ["Book", "Psychology", "Recommended"]),
    ("Data Patterns defense 40%.", ["DataPatterns", "Defense", "Electronics"]),
    ("Post-merge ETH -500K.", ["Deflationary", "Supply", "Scarcity"]),
    ("G-Sec 7.1% FAR.", ["Bonds", "GSec", "FAR"]),
    ("Buy <18 hold 18-25 sell >30.", ["Simple", "Valuation", "Nifty"]),
    ("Prestige Rs 15K Cr.", ["Prestige", "RealEstate", "PreSales"]),
    ("Lens Farcaster Nostr social.", ["Social", "Decentralized", "Protocol"]),
    ("India premium justified.", ["Premium", "Valuation", "EM"]),
    ("Gold monetization 2.0.", ["Monetization", "Household", "Scheme"]),
    ("MBA Rs 20L = Rs 2-3Cr.", ["Education", "ROI", "MBA"]),
    ("Tata Power Solar 4GW.", ["TataPower", "Solar", "PLI"]),
    ("MiCA India tax US legislation.", ["Regulation", "MiCA", "Clarity"]),
    ("E-commerce $200B tier 3-4.", ["Ecommerce", "Growth", "Tier3"]),
    ("Retail advantage time horizon.", ["Time", "Advantage", "Horizon"]),
    ("Happiest Minds digital-first.", ["HappiestMinds", "Digital", "Growth"]),
    ("RWA $16B to $16T 2030.", ["RWA", "Tokenization", "Growth"]),
    ("Hedge funds India must-own.", ["Hedge", "Allocation", "India"]),
    ("Gold +25% 2008 crash.", ["Stabilizer", "Crisis", "Insurance"]),
    ("Passive 50% US 15% India.", ["Passive", "Revolution", "Evidence"]),
    ("Oberoi luxury cyclical.", ["Oberoi", "Luxury", "Mumbai"]),
    ("DEX $200B self-custody.", ["DEX", "Volume", "SelfCustody"]),
    ("Semiconductor $10B 3 fabs.", ["Semiconductor", "Fab", "Mission"]),
    ("Wrong ULIP Rs 1-2Cr 30Y.", ["Cost", "Mistakes", "Advice"]),
    ("Piramal financial 30%.", ["Piramal", "Turnaround", "NBFC"]),
    ("Hardware wallet seed backup.", ["Security", "Hardware", "Practice"]),
    ("15 holidays 250 days.", ["Holidays", "NSE", "Days"]),
    ("Bars less liquid coins easier.", ["Coin", "Bar", "Practical"]),
    ("Right partner dual income.", ["Partner", "Dual", "Compatibility"]),
    ("Tata Chemicals soda ash.", ["TataChemicals", "SodaAsh", "EV"]),
    ("Start Bitcoin ETH DeFi.", ["Learning", "Basics", "Understanding"]),
    ("GDP: Svc 55% Ind 28%.", ["GDP", "Composition", "Services"]),
    ("Dividend reinvest 45%.", ["Dividend", "Reinvestment", "Compounding"]),
    ("Zydus biosimilar US.", ["Zydus", "Biosimilar", "Pharma"]),
    ("Token voting DAOs.", ["Governance", "DAO", "Decentralized"]),
    ("Processing behavioral edge.", ["Information", "Edge", "Behavioral"]),
    ("Physical digital ETF SGB.", ["Vehicles", "Comparison", "Choice"]),
    ("Buffett wife 90% index.", ["Buffett", "Index", "Simple"]),
    ("TCS Rs 15L Cr AI +$50B.", ["TCS", "IT", "AI"]),
    ("Trilemma scalability security.", ["Trilemma", "Tradeoffs", "Architecture"]),
    ("Consumer $2.5T +12%.", ["Consumer", "Spending", "Growth"]),
    ("Tax-loss harvesting offsets.", ["Tax", "Harvest", "Strategy"]),
    ("Bosch EV transition.", ["Bosch", "Auto", "EV"]),
    ("Multi-chain ETH SOL ATOM.", ["MultiChain", "Future", "Interoperable"]),
    ("50M demat 2Y.", ["Retail", "Demat", "Revolution"]),
    ("US 8133T India 812T.", ["Reserves", "CentralBank", "Allocation"]),
    ("'Different' expensive word.", ["Different", "Cycle", "Humble"]),
    ("Lemon Tree budget 25%.", ["LemonTree", "Hotel", "Travel"]),
    ("Modular wins.", ["Scalability", "Solutions", "Modular"]),
    ("Renewable 200GW 500 target.", ["Renewable", "Target", "Hydrogen"]),
    ("Recency bias overvalues.", ["Psychology", "Bias", "Valuations"]),
    ("LTTS engineering 25%.", ["LTTS", "Engineering", "R&D"]),
    ("Adoption UX regulation.", ["Adoption", "UX", "Institutional"]),
    ("90% from allocation.", ["Allocation", "Returns", "Big"]),
    ("Lightweight gold design.", ["Design", "Trends", "Modern"]),
    ("Network net worth.", ["Network", "Community", "Learning"]),
    ("Lightning micro-payments.", ["Lightning", "Micropayments", "Exchange"]),
    ("200B UPI > US+UK+EU.", ["UPI", "Payments", "Revolution"]),
    ("Sensex 16.5% 1979.", ["Sensex", "CAGR", "Resilient"]),
    ("Info Edge hidden Zomato.", ["InfoEdge", "Hidden", "Value"]),
    ("Custody $300B crypto.", ["Custody", "Institutional", "Safety"]),
    ("Semi-strong efficient.", ["Efficiency", "SemiStrong", "Information"]),
    ("Recycled 25% mining 75%.", ["Supply", "Mining", "Recycled"]),
    ("Edge triangle 3 analyses.", ["Edge", "Triangle", "Analysis"]),
    ("Affle AI 30%.", ["Affle", "AI", "Mobile"]),
    ("DeFi open no gatekeepers.", ["DeFi", "TradFi", "Redesigned"]),
    ("Urbanization 36→45%.", ["Urbanization", "Consumption", "Housing"]),
    ("20s learn 30s earn 40s grow.", ["Journey", "Decades", "Priority"]),
    ("CDSL 200M inclusion.", ["CDSL", "Demat", "Monopoly"]),
    ("EIPs decentralized protocol.", ["EIP", "Governance", "Protocol"]),
    ("1L 1979 = 50Cr.", ["Patience", "Sensex", "LongTerm"]),
    ("ETF LTCG 1Y 12.5%.", ["Tax", "ETF", "LTCG"]),
    ("Maximize savings rate.", ["Savings", "Gap", "Control"]),
    ("Piramal CDMO 20%.", ["Piramal", "CDMO", "Outsourcing"]),
    ("Metaverse VR/AR evolving.", ["Metaverse", "VR", "Evolution"]),
    ("Education 4.5% GDP.", ["Education", "GDP", "NEP"]),
    ("Positive expected value.", ["Gambling", "ExpectedValue", "Difference"]),
    ("Tata Elxsi auto health.", ["TataElxsi", "Design", "Technology"]),
    ("Four phases cycle.", ["Cycle", "Phases", "Timing"]),
    ("Sensex 16.5% diversify.", ["Compounding", "Sensex", "Diversification"]),
    ("Gold 75% LTV collateral.", ["Collateral", "Loan", "LTV"]),
    ("Drift 60/40→80/20 risk.", ["Rebalance", "Drift", "Risk"]),
    ("Tata Comms submarine.", ["TataComm", "Submarine", "Infra"]),
    ("Smart contract coverage.", ["Insurance", "Smart", "Contract"]),
    ("Productivity +8%.", ["Productivity", "Manufacturing", "MakeInIndia"]),
    ("Judge process results.", ["Luck", "Process", "Results"]),
    ("Bajaj Finserv growth.", ["BajajFinserv", "Holding", "Growth"]),
    ("CBDC stablecoins BTC.", ["Money", "CBDC", "Future"]),
    ("Rate cuts expand P/E.", ["Rates", "Valuation", "P/E"]),
    ("Regression $3400 fair.", ["Model", "FairValue", "Regression"]),
    ("Spend less index wait.", ["Simple", "Wealth", "Boring"]),
    ("Sonata digital 22%.", ["Sonata", "Digital", "MidCap"]),
    ("Tokenomics fundamentals.", ["Token", "Economics", "Fundamentals"]),
    ("CPI 4.2% supportive.", ["Inflation", "CPI", "RBI"]),
    ("Cash -50K at 5%.", ["Cost", "Cash", "Inflation"]),
    ("PVR Inox ATH premium.", ["PVR", "Cinema", "Recovery"]),
    ("Community most valuable.", ["Community", "Social", "Adoption"]),
    ("EMH not perfect.", ["EMH", "Efficiency", "Behavioral"]),
    ("Negative real rates gold.", ["RealRates", "Opportunity", "Negative"]),
    ("Self-mastery edge.", ["Self", "Emotions", "Mastery"]),
    ("JLR Defender bestsellers.", ["JLR", "Luxury", "Cash"]),
    ("TradFi DeFi merging.", ["Bridge", "TradFi", "DeFi"]),
    ("GST faceless assessment.", ["Tax", "GST", "Reform"]),
    ("10K SIP 30Y = 4.5Cr.", ["Consistency", "SIP", "Wealth"]),
    ("Blinkit profitable 8-min.", ["Blinkit", "QuickCommerce", "Profit"]),
    ("ETH rollups SOL parallel.", ["Scalability", "Roadmap", "MultiChain"]),
    ("Virtuous cycle 7% GDP.", ["Growth", "Virtuous", "Cycle"]),
    ("Gold hedging debasement.", ["Hedge", "Debasement", "Scarcity"]),
    ("Uncorrelated frontier.", ["Construction", "Correlation", "Efficient"]),
    ("KPIT automotive 30%.", ["KPIT", "Automotive", "Software"]),
    ("DAOs billions voting.", ["DAO", "Governance", "Treasury"]),
    ("65% under 35 peak 2040.", ["Demographic", "Youth", "Population"]),
    ("Survive permanent loss.", ["Survival", "Capital", "Compounding"]),
    ("Bajaj Finance 100M.", ["BajajFinance", "NBFC", "Retail"]),
    ("BTC gold ETH oil.", ["Institutional", "Thesis", "Digital"]),
    ("Time > timing.", ["Timing", "TimeIn", "Study"]),
    ("Gold INR depreciates.", ["Rupee", "Depreciation", "INR"]),
    ("Order: emergency term SIP.", ["Guide", "Order", "Priority"]),
    ("Piramal AUM Rs 60K Cr.", ["Piramal", "Financial", "Turnaround"]),
    ("Crypto regulation frameworks.", ["Regulation", "Future", "Clarity"]),
    ("100K km highways metro.", ["Infrastructure", "Highways", "Metro"]),
    ("Risk permanent not vol.", ["Risk", "Permanent", "Diversify"]),
    ("Tata Consumer premium 15%.", ["TataConsumer", "FMCG", "Premium"]),
    ("L1 L2 L3 modular.", ["Stack", "Modular", "Architecture"]),
    ("Sensex 14% 25Y=2.6Cr.", ["Compound", "Returns", "Wonder"]),
    ("Gold age/2 allocation.", ["Allocation", "Rule", "Age"]),
    ("Advisor +2-3% coaching.", ["Advisor", "Value", "Coaching"]),
    ("Data Patterns 40% defense.", ["DataPatterns", "Defense", "Export"]),
    ("NFT 2.0 utility RWA.", ["NFT", "Utility", "Evolution"]),
    ("Reserves 60% treasuries.", ["Reserves", "Composition", "Diversification"]),
    ("25:5K 35:15K 45:50K.", ["Early", "SIP", "Age"]),
    ("LTFH rural 20%.", ["LTFH", "Rural", "Housing"]),
    ("UseCases utility adoption.", ["UseCases", "Utility", "Adoption"]),
    ("Fed RBI ECB crucial.", ["CentralBanks", "Monetary", "Policy"]),
    ("1% rate -3% gold.", ["Sensitivity", "Rates", "Dollar"]),
    ("Munger moat price.", ["Checklist", "Munger", "Quality"]),
    ("Tata Steel India infra.", ["TataSteel", "India", "Focus"]),
    ("Trilemma solved modular.", ["Trilemma", "Solved", "Modular"]),
    ("India Stack world DPI.", ["IndiaStack", "Digital", "Infrastructure"]),
    ("Four quadrants cash flow.", ["CashFlow", "Quadrants", "Freedom"]),
    ("Cochin Rs 25K Cr.", ["CochinShipyard", "Navy", "Defense"]),
    ("Embedded tokenized.", ["Banking", "Future", "Embedded"]),
    ("2% monthly=27%.", ["Compounding", "Trading", "Monthly"]),
    ("Strategic reserve China.", ["Reserve", "Strategic", "Trend"]),
    ("TWR not MWR.", ["TWR", "Consistency", "Metric"]),
    ("Taj repositioning.", ["IndianHotels", "Taj", "Recovery"]),
    ("Spot futures options.", ["Structure", "Futures", "Options"]),
    ("GST 1L→2.1L.", ["GST", "Formalization", "Trend"]),
    ("100-baggers small cap.", ["SmallCap", "TenBagger", "Diversify"]),
    ("Trent Zudio 35%.", ["Trent", "Retail", "Growth"]),
    ("AI agents on-chain.", ["AI", "Crypto", "Convergence"]),
    ("Most tech advanced EM.", ["Microstructure", "Technology", "Evolution"]),
    ("22% households gold.", ["Emergency", "Cultural", "Savings"]),
    ("4-3-2-1 rule.", ["Rule", "Allocation", "Simple"]),
    ("Zomato 50K→2.5L.", ["Zomato", "MarketCap", "Platform"]),
    ("Web3 stack layers.", ["Web3", "Stack", "Layers"]),
    ("10M workforce/yr.", ["Demographic", "Workforce", "Opportunity"]),
    ("Index 0.1% active 1.5%.", ["Cost", "Products", "Comparison"]),
    ("Astral 25% premium.", ["Astral", "Pipes", "Brand"]),
    ("15 countries BTC legal.", ["Standard", "LegalTender", "Adoption"]),
    ("Three Ds growth.", ["Thesis", "Demographics", "Digitization"]),
    ("Gold drivers supportive.", ["Drivers", "2026", "Supportive"]),
    ("Patience most important.", ["Patience", "Conviction", "Reward"]),
    ("Tata Power solar.", ["TataPower", "Renewable", "Solar"]),
    ("IPFS Filecoin Arweave.", ["Decentralized", "Internet", "Web3"]),
    ("400M middle class.", ["MiddleClass", "Consumption", "Growth"]),
    ("Tax sheltered accounts.", ["Location", "Tax", "Efficiency"]),
    ("Bajaj Housing 30%.", ["BajajHousing", "HFC", "Growth"]),
    ("Social recovery wallets.", ["Wallet", "Evolution", "UX"]),
    ("Higher vol higher returns.", ["Volatility", "Returns", "Stomach"]),
    ("10% gold tail risk.", ["Insurance", "Tail", "Protection"]),
    ("Start Rs 500 SIP.", ["Misconception", "Start", "Habit"]),
    ("Laurus API 30%.", ["Laurus", "API", "ChinaPlus1"]),
    ("Self-sovereign identity.", ["Identity", "SelfSovereign", "Privacy"]),
    ("Rs 10L Cr capex.", ["Capex", "Multiplier", "Infrastructure"]),
    ("Avoid 50% loss=100%.", ["No", "Loss", "Prevention"]),
    ("Zudio disruptive.", ["Zudio", "FastFashion", "Disruptive"]),
    ("$300B stablecoins.", ["Stablecoin", "Revolution", "Payments"]),
    ("Cash 7% cost.", ["Cash", "Opportunity", "Cost"]),
    ("Gold +15% recessions.", ["Recession", "Insurance", "Probability"]),
    ("8th wonder 2.6Cr.", ["Compound", "Wonder", "Wealth"]),
    ("Piramal transformation.", ["Piramal", "Transformation", "Finance"]),
    ("Virtual real estate.", ["Metaverse", "Economy", "Virtual"]),
    ("Karnataka Maharashtra innovation.", ["Innovation", "Ecosystem", "Cities"]),
    ("Good buy great price.", ["Good", "Great", "Price"]),
    ("Bajaj Health 50%.", ["BajajFinserv", "Health", "Digital"]),
    ("L2 2026 L3 2027.", ["Scalability", "Timeline", "Maturity"]),
    ("AI analysis human decisions.", ["AI", "Analysis", "Decision"]),
    ("Dollar weakening deficits.", ["Currency", "Dollar", "Cycle"]),
    ("1% tax=30% wealth.", ["Tax", "Efficiency", "Wealth"]),
    ("KPIT auto 30%.", ["KPIT", "Automotive", "Software"]),
    ("DAO experiments.", ["Governance", "DAO", "Experiment"]),
    ("Penetration low growth.", ["Penetration", "Retail", "Growth"]),
    ("15Y SIPs more.", ["Decision", "SIP", "Consistency"]),
    ("Tata Rs 40L Cr.", ["Tata", "Group", "Conglomerate"]),
    ("Maturity custody.", ["Maturity", "Institutional", "Infrastructure"]),
    ("2% India if 5% $500B.", ["Allocation", "Global", "Flows"]),
    ("Tokenized gold stablecoins.", ["Future", "Tokenized", "Digital"]),
    ("Buy quality hold.", ["Wealth", "Quality", "Formula"]),
    ("Zomato-Blinkit Rs 2.5L.", ["Zomato", "Blinkit", "Platform"]),
    ("Bridges atomic swaps.", ["Interoperability", "Bridges", "Communication"]),
    ("PMI 62.3 highest.", ["PMI", "Manufacturing", "PLI"]),
    ("Financial freedom.", ["Freedom", "Goal", "Financial"]),
    ("Adani energy logistics.", ["Adani", "Portfolio", "Conglomerate"]),
    ("Open composable accessible.", ["Finance", "Open", "Accessible"]),
    ("Indian equity 40Y.", ["Compounding", "Equity", "Wealth"]),
    ("Gold monetary asset.", ["Gold", "Monetary", "Asset"]),
    ("Freedom choices wealth.", ["Freedom", "Choices", "Wealth"]),
    ("India 7% GDP.", ["India", "Growth", "Future"]),
    ("Blockchain trustless.", ["Blockchain", "Trust", "Revolution"]),
    ("Stay the course.", ["Patience", "History", "Rewarded"]),
    ("5000 years preservation.", ["Gold", "History", "Preservation"]),
    ("Start today.", ["Start", "Today", "Now"]),
]

# 80 poll templates
P = [
    ("Market outlook?", ["Bullish", "Bearish", "Sideways", "Unsure"], ["Markets", "Outlook", "Poll"]),
    ("Best sector Q2?", ["Banking", "IT", "Pharma", "Auto"], ["Sector", "Q2", "Poll"]),
    ("BTC $150K year-end?", ["Yes", "No", "Already did", "Unsure"], ["Bitcoin", "Price", "Poll"]),
    ("Portfolio equity %?", ["0-25%", "25-50%", "50-75%", "75-100%"], ["Equity", "Allocation", "Poll"]),
    ("Gold Rs 80K 2026?", ["Yes Q2", "Yes Q4", "No", "Already"], ["Gold", "Price", "Poll"]),
    ("India growth length?", ["10Y", "20Y", "50Y", "Forever"], ["India", "Growth", "Poll"]),
    ("Best dividend?", ["Coal India", "ITC", "Power Grid", "ONGC"], ["Dividend", "Income", "Poll"]),
    ("Best L1 2026?", ["Ethereum", "Solana", "Avalanche", "Other"], ["L1", "Performance", "Poll"]),
    ("Monthly SIP?", ["<5000", "5K-15K", "15K-50K", ">50K"], ["SIP", "Monthly", "Poll"]),
    ("Buy dip?", ["Now", "Wait 5%", "Wait 10%", "Bought"], ["Dip", "Buy", "Poll"]),
    ("Best long-term?", ["TCS", "HDFC", "Reliance", "Bajaj"], ["LongTerm", "Wealth", "Poll"]),
    ("Crypto hedge?", ["Yes", "No", "Sometimes", "Unsure"], ["Inflation", "Hedge", "Poll"]),
    ("Physical or ETF?", ["Physical", "ETF", "SGB", "Digital"], ["Gold", "Preference", "Poll"]),
    ("RBI cut 2026?", ["50 bps", "25 bps", "No", "Hike"], ["RBI", "Rates", "Poll"]),
    ("Barrier to investing?", ["Knowledge", "Money", "Fear", "None"], ["Barrier", "Investing", "Poll"]),
    ("Small or large 2026?", ["Small", "Large", "Mid", "Mix"], ["Cap", "2026", "Poll"]),
    ("ETH flip BTC?", ["5Y", "10Y", "Never", "Did"], ["ETH", "BTC", "Poll"]),
    ("Biggest position?", ["Nifty ETF", "Banking", "IT", "Gold"], ["Position", "Holdings", "Poll"]),
    ("Check freq?", ["Daily", "Weekly", "Monthly", "Rarely"], ["Frequency", "Portfolio", "Poll"]),
    ("Best gold vehicle?", ["SGB", "ETF", "Digital", "Coins"], ["Gold", "Invest", "Poll"]),
    ("Crypto use case?", ["DeFi", "NFTs", "Payments", "RWA"], ["UseCase", "Crypto", "Poll"]),
    ("Best Tata?", ["TCS", "Motors", "Steel", "Power"], ["Tata", "Stock", "Poll"]),
    ("India driver 2026?", ["Mfg", "Services", "Infra", "Consumption"], ["Growth", "Driver", "Poll"]),
    ("Advisor?", ["Active", "Rare", "Self", "Planning"], ["Advisor", "Planning", "Poll"]),
    ("Biggest risk?", ["Recession", "Geopolitical", "Valuation", "Regulatory"], ["Risk", "2026", "Poll"]),
    ("Nifty target?", ["27K", "28K", "30K", "Correction"], ["Nifty", "Target", "Poll"]),
    ("Best mid-cap?", ["Trent", "Zomato", "KPIT", "Persistent"], ["MidCap", "Stock", "Poll"]),
    ("Gold or silver?", ["Gold", "Silver", "Both", "Neither"], ["Gold", "Silver", "Poll"]),
    ("Best bank stock?", ["HDFC", "ICICI", "SBI", "Kotak"], ["Banking", "Stock", "Poll"]),
    ("FII impact?", ["Very high", "Moderate", "Low", "None"], ["FII", "Impact", "Poll"]),
    ("Crypto regulation?", ["Helpful", "Harmful", "Late", "Early"], ["Regulation", "Crypto", "Poll"]),
    ("Best debt?", ["G-Sec", "Corporate", "FD", "PPF"], ["Debt", "Instrument", "Poll"]),
    ("PSU rally?", ["Yes", "No", "Partial", "Sector"], ["PSU", "Rally", "Poll"]),
    ("IT recovery?", ["Strong", "Weak", "Mixed", "Early"], ["IT", "Recovery", "Poll"]),
    ("Real estate?", ["Buy now", "Wait", "REITs", "Avoid"], ["RealEstate", "Invest", "Poll"]),
    ("Best pharma?", ["Sun", "Dr Reddy", "Cipla", "Divis"], ["Pharma", "Stock", "Poll"]),
    ("India vs China?", ["India", "China", "Both", "Neither"], ["India", "China", "Poll"]),
    ("Best small cap?", ["Route", "Affle", "Happiest", "Mphasis"], ["SmallCap", "Pick", "Poll"]),
    ("SIP adequate?", ["Yes", "Need more", "Way more", "Unsure"], ["SIP", "Adequate", "Poll"]),
    ("Auto outlook?", ["Bullish", "Bearish", "Neutral", "Stock-specific"], ["Auto", "Outlook", "Poll"]),
    ("Energy transition?", ["Fast", "Slow", "Accelerating", "Too slow"], ["Energy", "Transition", "Poll"]),
    ("F&O strategy?", ["Straddle", "Strangle", "Condor", "Directional"], ["F&O", "Strategy", "Poll"]),
    ("India infra quality?", ["Excellent", "Good", "Improving", "Poor"], ["Infrastructure", "Quality", "Poll"]),
    ("MF selection?", ["Returns", "Risk", "Manager", "Expense"], ["MF", "Selection", "Poll"]),
    ("Recession prob?", ["<20%", "20-40%", "40-60%", ">60%"], ["Recession", "Probability", "Poll"]),
    ("Digital India impact?", ["Transformative", "Moderate", "Minimal", "Hype"], ["Digital", "Impact", "Poll"]),
    ("Dividend vs growth?", ["Dividend", "Growth", "Balanced", "Depends"], ["Dividend", "Growth", "Poll"]),
    ("Best commodity?", ["Gold", "Silver", "Crude", "Copper"], ["Commodity", "Play", "Poll"]),
    ("Correction coming?", ["<5%", "5-10%", ">10%", "No"], ["Correction", "Market", "Poll"]),
    ("Best education?", ["MBA", "Coding", "Design", "Finance"], ["Education", "Investment", "Poll"]),
    ("IPO worth it?", ["Always", "Selective", "Never", "Depends"], ["IPO", "Subscription", "Poll"]),
    ("Bond yields?", ["Higher", "Lower", "Same", "Volatile"], ["Bonds", "Yields", "Poll"]),
    ("Best insurance?", ["Term", "Health", "ULIP", "Endowment"], ["Insurance", "Type", "Poll"]),
    ("Rebalance freq?", ["Monthly", "Quarterly", "Annual", "Never"], ["Rebalance", "Frequency", "Poll"]),
    ("Best global ETF?", ["S&P500", "Nasdaq", "World", "EM"], ["ETF", "Global", "Poll"]),
    ("AI jobs impact?", ["High", "Medium", "Low", "Positive"], ["AI", "Jobs", "Poll"]),
    ("Gold allocation %?", ["5%", "10%", "15%", "20%"], ["Gold", "Allocation", "Poll"]),
    ("Income strategy?", ["Dividends", "Rent", "Interest", "Trading"], ["Income", "Strategy", "Poll"]),
    ("PSU privatization?", ["All", "Some", "None", "Started"], ["PSU", "Privatization", "Poll"]),
    ("Timing possible?", ["Yes", "No", "Sometimes", "Rarely"], ["Timing", "Market", "Poll"]),
    ("GDP 8% 2027?", ["Yes", "No", "Close", "Exceed"], ["GDP", "2027", "Poll"]),
    ("Best gold scheme?", ["SGB", "Sovereign", "ETF", "Digital"], ["Gold", "Scheme", "Poll"]),
    ("Crypto wallet?", ["Hardware", "Software", "Custodial", "Multi-sig"], ["Wallet", "Type", "Poll"]),
    ("Best retirement?", ["NPS", "PPF", "ELSS", "EPF"], ["Retirement", "Plan", "Poll"]),
    ("Sentiment?", ["Greedy", "Fearful", "Neutral", "Confused"], ["Sentiment", "Market", "Poll"]),
    ("Best sectoral fund?", ["Banking", "IT", "Pharma", "Auto"], ["Sectoral", "Fund", "Poll"]),
    ("F&O profitable?", ["Yes", "No", "Sometimes", "Depends"], ["F&O", "Profitable", "Poll"]),
    ("Best tax-save?", ["ELSS", "PPF", "NPS", "Insurance"], ["Tax", "Saving", "Poll"]),
    ("Market overvalued?", ["Yes", "No", "Fair", "Sector"], ["Valuation", "Market", "Poll"]),
    ("Best fixed income?", ["FD", "G-Sec", "Corporate", "PPF"], ["Fixed", "Income", "Poll"]),
    ("FDI rank?", ["#1", "#2", "#3", "Top 5"], ["FDI", "India", "Poll"]),
    ("Best AI stock?", ["TCS", "Infosys", "HCL", "Wipro"], ["AI", "Stock", "Poll"]),
    ("Gold 2027?", ["$3000", "$3500", "$4000", "$5000"], ["Gold", "Price2027", "Poll"]),
    ("Rebalance now?", ["Yes", "No", "Wait", "Done"], ["Rebalance", "Now", "Poll"]),
    ("Best platform?", ["Zerodha", "Groww", "Upstox", "Angel"], ["Platform", "Trading", "Poll"]),
    ("Mfg boom?", ["Yes", "Starting", "No", "Hype"], ["Manufacturing", "Boom", "Poll"]),
    ("Crypto winter over?", ["Yes", "No", "Partially", "Wasn't"], ["Crypto", "Winter", "Poll"]),
    ("Best health cover?", ["Star", "HDFC Ergo", "Niva", "ICICI"], ["Health", "Insurance", "Poll"]),
    ("Market bottomed?", ["Yes", "No", "Close", "Far"], ["Market", "Bottom", "Poll"]),
    ("Best intl fund?", ["Franklin", "Motilal", "ICICI", "Edelweiss"], ["International", "Fund", "Poll"]),
    ("PSU to hold?", ["SBI", "ONGC", "Coal India", "NTPC"], ["PSU", "Hold", "Poll"]),
    ("2026 return?", ["10%", "15%", "20%", ">20%"], ["Market", "Return2026", "Poll"]),
]

L = [
    ("India monetary analysis.", "https://economictimes.indiatimes.com/markets/analysis", ["Monetary", "Analysis", "Read"]),
    ("SEBI F&O breakdown.", "https://sebi.gov.in/sebiweb/home/HomeAction.do", ["SEBI", "F&O", "Regulation"]),
    ("WEF: 86% blockchain 2028.", "https://weforum.org/blockchain-report-2026", ["WEF", "Blockchain", "Report"]),
    ("IMF: India 7.2%.", "https://imf.org/weo-reports/2026", ["IMF", "Growth", "Outlook"]),
    ("RBI savings report.", "https://rbi.org.in/annualreport", ["RBI", "Savings", "Report"]),
]

def rdate():
    return datetime.now() - timedelta(days=random.randint(0,30), hours=random.randint(0,23), minutes=random.randint(0,59))

def reng():
    return random.randint(50,5000), random.randint(5,500), random.randint(10,1000)

def fmt(dt):
    return f"new Date({int(dt.timestamp()*1000)}).toISOString()"

def esc(s):
    return s.replace("'", "\\'")

def tp(i, a, ct):
    text, tags = ct
    dt = rdate(); l,c,s = reng()
    return f"    {{\n      id: 'p{i:03d}',\n      author: {{ name: '{a['name']}', avatar: '{a['avatar']}', verified: {str(a['verified']).lower()}, bio: '{esc(a['bio'])}' }},\n      content: '{esc(text)}',\n      images: [],\n      publishDate: {fmt(dt)},\n      likes: {l}, comments: {c}, shares: {s},\n      bookmarked: false, type: 'text',\n      tags: {json.dumps(tags)}\n    }}"

def pp(i, a, ct):
    q, opts, tags = ct
    dt = rdate(); l,c,s = reng()
    o = ", ".join([f'{{ text: \'{o}\', votes: {random.randint(500,6000)} }}' for o in opts])
    return f"    {{\n      id: 'p{i:03d}',\n      author: {{ name: '{a['name']}', avatar: '{a['avatar']}', verified: {str(a['verified']).lower()}, bio: '{esc(a['bio'])}' }},\n      content: '{esc(q)}',\n      images: [],\n      publishDate: {fmt(dt)},\n      likes: {l}, comments: {c}, shares: {s},\n      bookmarked: false, type: 'poll',\n      pollOptions: [{o}],\n      tags: {json.dumps(tags)}\n    }}"

def lp(i, a, ct):
    text, url, tags = ct
    dt = rdate(); l,c,s = reng()
    return f"    {{\n      id: 'p{i:03d}',\n      author: {{ name: '{a['name']}', avatar: '{a['avatar']}', verified: {str(a['verified']).lower()}, bio: '{esc(a['bio'])}' }},\n      content: '{esc(text)}',\n      images: [],\n      publishDate: {fmt(dt)},\n      likes: {l}, comments: {c}, shares: {s},\n      bookmarked: false, type: 'link',\n      linkUrl: '{url}',\n      tags: {json.dumps(tags)}\n    }}"

# Original 31 posts (preserved exactly)
ORIG = '''    {
      id: 'p001',
      author: { name: 'Sarah Mitchell', avatar: '👩\u200d💼', verified: true, bio: 'Anchor at Bloomberg' },
      content: 'BREAKING: Fed holds rates at 4.25%-4.50%. Powell signals September cut possible if data cooperates. Markets initially volatile but settling. Key takeaway: the dot plot now shows 2 cuts in 2026, up from 1 previously. Thread on implications.',
      images: [],
      publishDate: new Date(Date.now() - 30 * 60000).toISOString(),
      likes: 4523, comments: 892, shares: 2341,
      bookmarked: false, type: 'text',
      tags: ['FederalReserve', 'InterestRates', 'Markets']
    },
    {
      id: 'p002',
      author: { name: 'Rajeev Chandrasekhar', avatar: '🇮🇳', verified: true, bio: 'Former Minister of State for IT, India' },
      content: 'India GDP at 7.8% - not just a number, it represents the collective ambition of 1.4 billion people. When the world slows down, India accelerates. This is what structural reform looks like. Digital India, Make in India, Skill India - all converging.',
      images: [],
      publishDate: new Date(Date.now() - 50 * 60000).toISOString(),
      likes: 12800, comments: 2340, shares: 5670,
      bookmarked: false, type: 'text',
      tags: ['India', 'GDP', 'Economy', 'Modi']
    },
    {
      id: 'p003',
      author: { name: 'Vitalik Buterin', avatar: '🔷', verified: true, bio: 'Ethereum co-founder' },
      content: 'Ethereum Dawn is live. Full sharding on L1. Gas fees dropped 95%. This is what we promised in 2015. The future is here. ETH is now scalable, secure, AND decentralized. The triple trilemma is solved.',
      images: [],
      publishDate: new Date(Date.now() - 120 * 60000).toISOString(),
      likes: 89000, comments: 15600, shares: 34000,
      bookmarked: false, type: 'text',
      tags: ['Ethereum', 'Dawn', 'GasFees', 'Crypto']
    },
    {
      id: 'p004',
      author: { name: 'Chamath Palihapitiya', avatar: '🚀', verified: true, bio: 'Investor, Social Capital CEO' },
      content: 'I just sold 40% of my NVDA position. Before you judge - I still hold a massive position. But when a single company accounts for 12% of the S&P 500 market cap, you take some chips off the table. The AI revolution is real but so is concentration risk.',
      images: [],
      publishDate: new Date(Date.now() - 180 * 60000).toISOString(),
      likes: 23400, comments: 4560, shares: 8900,
      bookmarked: false, type: 'text',
      tags: ['NVIDIA', 'AI', 'Investing', 'Portfolio']
    },
    {
      id: 'p005',
      author: { name: 'Harsha Bhogle', avatar: '🏏', verified: true, bio: 'Cricket commentator and analyst' },
      content: 'Kohli 147 at Sydney. In a chase of 328. In what might be one of his last Tests. The greatest chase master of his generation delivers when it matters most. Border-Gavaskar Trophy stays with India. 3-1. Simply magnificent.',
      images: [],
      publishDate: new Date(Date.now() - 500 * 60000).toISOString(),
      likes: 156000, comments: 28000, shares: 67000,
      bookmarked: false, type: 'text',
      tags: ['Cricket', 'Kohli', 'India', 'BorderGavaskar']
    },
    {
      id: 'p006',
      author: { name: 'Naval Ravikant', avatar: '🧘', verified: true, bio: 'Angel investor, philosopher' },
      content: 'AI will not replace humans. Humans who use AI will replace humans who dont. The most important skill for the next decade is knowing how to ask the right questions, not knowing the right answers.',
      images: [],
      publishDate: new Date(Date.now() - 300 * 60000).toISOString(),
      likes: 67800, comments: 4500, shares: 23400,
      bookmarked: false, type: 'text',
      tags: ['AI', 'FutureOfWork', 'Philosophy']
    },
    {
      id: 'p007',
      author: { name: 'Sadhguru', avatar: '🧘\u200d♂', verified: true, bio: 'Author, yogi, mystic' },
      content: 'Mars landing is wonderful. But lets not forget the Earth we already have. The first billion dollar investment should be in making this planet sustainable. The universe is not going anywhere. But our forests, rivers and soil might.',
      images: [],
      publishDate: new Date(Date.now() - 240 * 60000).toISOString(),
      likes: 234000, comments: 18000, shares: 89000,
      bookmarked: false, type: 'text',
      tags: ['Mars', 'Environment', 'Sustainability']
    },
    {
      id: 'p008',
      author: { name: 'Bloomberg Markets', avatar: '📊', verified: true, bio: 'Global financial news and data' },
      content: 'MARKET PULSE: Sensex -342 (-0.41%) | NIFTY -98 (-0.39%) | Dow +156 (+0.31%) | NASDAQ +234 (+1.26%) | Bitcoin $121,456 (+2.74%) | Gold $3,245 (+0.90%) | Brent $97.45 (+3.40%)',
      images: [],
      publishDate: new Date(Date.now() - 15 * 60000).toISOString(),
      likes: 8900, comments: 1200, shares: 3400,
      bookmarked: false, type: 'text',
      tags: ['Markets', 'Sensex', 'Dow', 'Bitcoin']
    },
    {
      id: 'p009',
      author: { name: 'Anand Mahindra', avatar: '🏭', verified: true, bio: 'Chairman of Mahindra Group' },
      content: 'When I see Ziva Dhoni sign for Rs 16 crore, I see more than cricket. I see the power of legacy, mentorship, and the IPL ecosystem creating opportunities for the next generation. India doesnt just play cricket - it builds futures.',
      images: [],
      publishDate: new Date(Date.now() - 360 * 60000).toISOString(),
      likes: 89000, comments: 6700, shares: 34000,
      bookmarked: false, type: 'text',
      tags: ['IPL', 'Dhoni', 'Cricket', 'India']
    },
    {
      id: 'p010',
      author: { name: 'Cathie Wood', avatar: '📈', verified: true, bio: 'CEO & CIO, ARK Invest' },
      content: 'Our conviction in AI has never been higher. GPT-5, Llama 4, Gemini 3.0 - all released in the same month. The convergence of compute, data, and algorithms is creating an intelligence explosion. We are increasing our AI exposure by 25%.',
      images: [],
      publishDate: new Date(Date.now() - 420 * 60000).toISOString(),
      likes: 34500, comments: 5600, shares: 12000,
      bookmarked: false, type: 'text',
      tags: ['AI', 'ARKInvest', 'Investing', 'Tech']
    },
    {
      id: 'p011',
      author: { name: 'Narendra Modi', avatar: '🇮🇳', verified: true, bio: 'Prime Minister of India' },
      content: 'Digital India 2.0 is not just a policy - its a movement. Rs 50,000 crore dedicated to making India the AI capital of the world. 10 million new digital jobs. 22 languages in BharatGPT. This is our moment. #DigitalIndia2 #AtmanirbharBharat',
      images: [],
      publishDate: new Date(Date.now() - 480 * 60000).toISOString(),
      likes: 567000, comments: 45000, shares: 189000,
      bookmarked: false, type: 'text',
      tags: ['DigitalIndia', 'AI', 'India', 'Modi']
    },
    {
      id: 'p012',
      author: { name: 'Nassim Nicholas Taleb', avatar: '📚', verified: true, bio: 'Author of The Black Swan' },
      content: 'The Nikkei crash (-12%) is not a black swan. Its a grey rhino. Yen carry trade unwind was predictable. The question is: how many portfolio managers had proper hedging? My guess: fewer than 10%.',
      images: [],
      publishDate: new Date(Date.now() - 20 * 60000).toISOString(),
      likes: 45600, comments: 7800, shares: 18900,
      bookmarked: false, type: 'text',
      tags: ['Nikkei', 'RiskManagement', 'Japan', 'Markets']
    },
    {
      id: 'p013',
      author: { name: 'Adani Group', avatar: '🏭', verified: true, bio: "India's leading infrastructure conglomerate" },
      content: 'Market cap crosses $400 billion. Adani Green hits all-time high. Adani Ports handles record cargo. The Adani story is Indias story - ambitious, resilient, and unstoppable. Thank you to 400 million shareholders.',
      images: [],
      publishDate: new Date(Date.now() - 550 * 60000).toISOString(),
      likes: 34000, comments: 8900, shares: 12000,
      bookmarked: false, type: 'text',
      tags: ['Adani', 'IndianStocks', 'Markets']
    },
    {
      id: 'p014',
      author: { name: 'Balaji Srinivasan', avatar: '🌐', verified: true, bio: 'Technologist, investor, writer' },
      content: 'UPI at 20 billion transactions/month. Digital Rupee 2.0 with smart contracts. Aadhaar covering 1.4 billion. India is running the largest fintech experiment in human history and its actually working.',
      images: [],
      publishDate: new Date(Date.now() - 600 * 60000).toISOString(),
      likes: 56700, comments: 3400, shares: 18900,
      bookmarked: false, type: 'text',
      tags: ['UPI', 'DigitalRupee', 'India', 'Fintech']
    },
    {
      id: 'p015',
      author: { name: 'Warren Buffett Quotes', avatar: '💬', verified: false, bio: 'Daily wisdom from the Oracle of Omaha' },
      content: 'BE FEARFUL WHEN OTHERS ARE GREEDY AND GREEDY WHEN OTHERS ARE FEARFUL. With Nikkei -12%, Dow -2000, and AI bubble warnings, this might be the fear Buffett was talking about.',
      images: [],
      publishDate: new Date(Date.now() - 25 * 60000).toISOString(),
      likes: 78900, comments: 4500, shares: 34000,
      bookmarked: false, type: 'text',
      tags: ['Buffett', 'ValueInvesting', 'Markets']
    },
    {
      id: 'p016',
      author: { name: 'Rohit Sharma', avatar: '🏏', verified: true, bio: 'Indian cricket team captain' },
      content: 'Champions! Border-Gavaskar Trophy stays with India. 3-1. Special mention to @imVkohli for that incredible century at Sydney. This team never gives up. Thank you India for your support. Jai Hind! 🇮🇳',
      images: [],
      publishDate: new Date(Date.now() - 520 * 60000).toISOString(),
      likes: 234000, comments: 45000, shares: 89000,
      bookmarked: false, type: 'text',
      tags: ['Cricket', 'India', 'BorderGavaskar', 'Kohli']
    },
    {
      id: 'p017',
      author: { name: 'Markets Today', avatar: '💹', verified: true, bio: 'Real-time market updates' },
      content: 'SURVEY: Where do you think Sensex will close tomorrow? Reply with your prediction!',
      images: [],
      publishDate: new Date(Date.now() - 60 * 60000).toISOString(),
      likes: 2340, comments: 4560, shares: 230,
      bookmarked: false, type: 'poll',
      pollOptions: [
        { text: 'Above 83,000', votes: 3400 },
        { text: '82,000 - 83,000', votes: 5600 },
        { text: '81,000 - 82,000', votes: 2100 },
        { text: 'Below 81,000', votes: 800 }
      ],
      tags: ['Sensex', 'Poll', 'Markets']
    },
    {
      id: 'p018',
      author: { name: 'Crypto India', avatar: '🪙', verified: true, bio: 'Indias largest crypto community' },
      content: 'Bitcoin at $120,000. Remember when people said it was dead? 2026 is shaping up to be the year of institutional crypto adoption. BlackRock ETF inflows hit $2.1B in a single day.',
      images: [],
      publishDate: new Date(Date.now() - 200 * 60000).toISOString(),
      likes: 34500, comments: 5600, shares: 12000,
      bookmarked: false, type: 'text',
      tags: ['Bitcoin', 'Crypto', 'India', 'ETF']
    },
    {
      id: 'p019',
      author: { name: 'Elon Musk', avatar: '🚀', verified: true, bio: 'Mars, Cars & Mars Cars' },
      content: 'First humans on Mars. Humanity is a multi-planetary species. Next stop: Mars base by 2030. Congratulations to the SpaceX team and the brave crew of Horizon.',
      images: [],
      publishDate: new Date(Date.now() - 185 * 60000).toISOString(),
      likes: 567000, comments: 89000, shares: 234000,
      bookmarked: false, type: 'text',
      tags: ['Mars', 'SpaceX', 'Humans', 'Space']
    },
    {
      id: 'p020',
      author: { name: 'Shashi Tharoor', avatar: '📖', verified: true, bio: 'Author, MP, former diplomat' },
      content: 'India overtakes Japan as the 3rd largest economy. A nation that was colonized 79 years ago is now economically larger than the nation that colonized much of Asia. From $18 billion GDP in 1947 to $5.3 trillion. The Indian story is unprecedented.',
      images: [],
      publishDate: new Date(Date.now() - 40 * 60000).toISOString(),
      likes: 189000, comments: 12000, shares: 67000,
      bookmarked: false, type: 'text',
      tags: ['India', 'GDP', 'Economy', 'Japan']
    },
    {
      id: 'p021',
      author: { name: 'Priyanka Chopra', avatar: '🎬', verified: true, bio: 'Actor, Producer, Entrepreneur' },
      content: 'Bollywood making history again! Chakra crosses Rs 2800 crore worldwide in 10 days. Rajamouli ji, you did it again. Indian cinema is truly global now. So proud!',
      images: [],
      publishDate: new Date(Date.now() - 680 * 60000).toISOString(),
      likes: 345000, comments: 23000, shares: 89000,
      bookmarked: false, type: 'text',
      tags: ['Bollywood', 'Chakra', 'Rajamouli', 'Cinema']
    },
    {
      id: 'p022',
      author: { name: 'Sundar Pichai', avatar: '🧠', verified: true, bio: 'CEO of Google & Alphabet' },
      content: 'Gemini 3.0 Ultra is here. 10M token context window. PhD-level reasoning. This is what happens when you invest in fundamental research for a decade. Proud of the DeepMind team.',
      images: [],
      publishDate: new Date(Date.now() - 750 * 60000).toISOString(),
      likes: 123000, comments: 8900, shares: 45000,
      bookmarked: false, type: 'text',
      tags: ['Google', 'Gemini', 'AI', 'DeepMind']
    },
    {
      id: 'p023',
      author: { name: 'Zerodha', avatar: '💹', verified: true, bio: 'Indias largest stock broking platform' },
      content: 'Nifty Bank at all-time high. PSU banks up 15% in a month. Government privatization plans fueling the rally. Are you positioned for the next leg?',
      images: [],
      publishDate: new Date(Date.now() - 390 * 60000).toISOString(),
      likes: 23400, comments: 3400, shares: 8900,
      bookmarked: false, type: 'text',
      tags: ['NiftyBank', 'PSU', 'StockMarket', 'India']
    },
    {
      id: 'p024',
      author: { name: 'Tim Cook', avatar: '🍎', verified: true, bio: 'CEO of Apple' },
      content: 'Vision Pro 2: Half the price, all the magic. The neural interface changes everything. Available this fall. We cant wait to see what developers build.',
      images: [],
      publishDate: new Date(Date.now() - 365 * 60000).toISOString(),
      likes: 234000, comments: 12000, shares: 67000,
      bookmarked: false, type: 'text',
      tags: ['Apple', 'VisionPro', 'NeuralInterface']
    },
    {
      id: 'p025',
      author: { name: 'Kiran Mazumdar-Shaw', avatar: '💊', verified: true, bio: 'Chairperson, Biocon' },
      content: 'CRISPR cure for sick cell disease approved by FDA. This is the beginning of genetic medicine revolution. India must invest in biotech manufacturing to bring these therapies to our patients at affordable prices.',
      images: [],
      publishDate: new Date(Date.now() - 450 * 60000).toISOString(),
      likes: 45600, comments: 2300, shares: 12000,
      bookmarked: false, type: 'text',
      tags: ['CRISPR', 'Healthcare', 'FDA', 'India']
    },
    {
      id: 'p026',
      author: { name: 'Tarun Tahiliani', avatar: '🎨', verified: true, bio: 'Fashion designer and entrepreneur' },
      content: 'SURVEY: What is your preferred investment during market volatility?',
      images: [],
      publishDate: new Date(Date.now() - 700 * 60000).toISOString(),
      likes: 1200, comments: 3400, shares: 120,
      bookmarked: false, type: 'poll',
      pollOptions: [
        { text: 'Gold', votes: 6700 },
        { text: 'Fixed Deposits', votes: 3400 },
        { text: 'Blue Chip Stocks', votes: 4500 },
        { text: 'Cryptocurrency', votes: 2100 }
      ],
      tags: ['Investing', 'Poll', 'Gold', 'Stocks']
    },
    {
      id: 'p027',
      author: { name: 'Satya Nadella', avatar: '💻', verified: true, bio: 'Chairman and CEO, Microsoft' },
      content: 'Copilot 2.0 is not just a coding assistant. Its a software engineer. It can write, debug, test, and deploy entire applications. The future of software development is collaborative: human creativity + AI execution.',
      images: [],
      publishDate: new Date(Date.now() - 800 * 60000).toISOString(),
      likes: 89000, comments: 6700, shares: 34000,
      bookmarked: false, type: 'text',
      tags: ['Microsoft', 'Copilot', 'AI', 'Coding']
    },
    {
      id: 'p028',
      author: { name: 'Nikhil Kamath', avatar: '💰', verified: true, bio: 'Co-founder, Zerodha & True Beacon' },
      content: 'My contrarian take: the AI bubble warning from Goldman is actually bullish. When mainstream banks start warning about bubbles, its usually 12-18 months too early. The AI trade has at least 2 more years to run.',
      images: [],
      publishDate: new Date(Date.now() - 440 * 60000).toISOString(),
      likes: 56700, comments: 8900, shares: 23000,
      bookmarked: false, type: 'text',
      tags: ['AI', 'Bubble', 'Contrarian', 'Investing']
    },
    {
      id: 'p029',
      author: { name: 'Gaurav Chaudhary', avatar: '🔧', verified: true, bio: 'Tech YouTuber, 20M+ subscribers' },
      content: 'Samsung Galaxy S26 with on-device AI is INSANE. Drafts emails, summarizes meetings, even negotiates appointments. This is what happens when you put a real AI on a phone. Apple should be worried.',
      images: [],
      publishDate: new Date(Date.now() - 2250 * 60000).toISOString(),
      likes: 234000, comments: 12000, shares: 56000,
      bookmarked: false, type: 'text',
      tags: ['Samsung', 'GalaxyS26', 'AI', 'Smartphone']
    },
    {
      id: 'p030',
      author: { name: 'Raghuram Rajan', avatar: '🏦', verified: true, bio: 'Former RBI Governor, Professor at Chicago Booth' },
      content: 'RBI cutting rates while the Fed holds is the right move. With inflation at 3.2%, India has room to ease. But the real test is whether lower rates translate into higher credit growth or just asset price inflation.',
      images: [],
      publishDate: new Date(Date.now() - 2500 * 60000).toISOString(),
      likes: 34500, comments: 4500, shares: 12000,
      bookmarked: false, type: 'text',
      tags: ['RBI', 'InterestRates', 'India', 'Economy']
    },
    {
      id: 'p031',
      author: { name: 'Nithin Kamath', avatar: '📊', verified: true, bio: 'CEO, Zerodha' },
      content: 'Dow at 50,000 for the first time ever. From 0 to 10,000 took 80 years. From 40,000 to 50,000 took 3 years. The velocity of market gains is accelerating. Stay invested, stay humble.',
      images: [],
      publishDate: new Date(Date.now() - 35 * 60000).toISOString(),
      likes: 45600, comments: 3400, shares: 18000,
      bookmarked: false, type: 'text',
      tags: ['DowJones', 'StockMarket', 'Investing']
    }'''

def main():
    filepath = r'C:\Users\AICOE 5\Downloads\The Daily Yield\DailyYield\data\postsData.js'

    random.seed(42)
    posts = []
    idx = 32

    # 301 text
    for i in range(301):
        posts.append(tp(idx, AUTHORS[i % len(AUTHORS)], T[i % len(T)]))
        idx += 1
    # 44 extra text
    for i in range(44):
        posts.append(tp(idx, AUTHORS[(i+11) % len(AUTHORS)], T[(i+50) % len(T)]))
        idx += 1
    # 100 poll
    for i in range(100):
        posts.append(pp(idx, AUTHORS[(i+3) % len(AUTHORS)], P[i % len(P)]))
        idx += 1
    # 25 link
    for i in range(25):
        posts.append(lp(idx, AUTHORS[(i+7) % len(AUTHORS)], L[i % len(L)]))
        idx += 1

    random.shuffle(posts)

    output = f"""'use strict';

(function() {{
  var posts = [
{ORIG},
{chr(10).join(posts)}
  ];

  window.PostsData = {{
    posts: posts,
    getByType: function(type) {{ return posts.filter(function(p) {{ return p.type === type; }}); }},
    getPolls: function() {{ return posts.filter(function(p) {{ return p.type === 'poll'; }}); }},
    getMostLiked: function(n) {{
      n = n || 10;
      return posts.slice().sort(function(a, b) {{ return b.likes - a.likes; }}).slice(0, n);
    }},
    getRecent: function(n) {{
      n = n || 10;
      return posts.slice().sort(function(a, b) {{ return new Date(b.publishDate) - new Date(a.publishDate); }}).slice(0, n);
    }},
    getById: function(id) {{ return posts.find(function(p) {{ return p.id === id; }}); }}
  }};
}})();"""

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(output)

    import os
    sz = os.path.getsize(filepath)
    print(f"Total posts: {len(posts) + 31}")
    print(f"  Original: 31")
    print(f"  Text: {301+44}")
    print(f"  Poll: {100}")
    print(f"  Link: {25}")
    print(f"  New total: {len(posts)}")
    print(f"File size: {sz:,} bytes ({sz/1024:.0f} KB)")

if __name__ == "__main__":
    main()
